### ISSUE TITLE
Validation data finalisation

### ISSUE THREAD

**Issue by matthipsey** [AquaticEcoDynamics/Hawkesbury#2]
Resave agency/campaign different data:

**SWC**               (normal + us/ds)
**SWC-ww**        (wet weather campaign )
**DPIE-bouy**     (EES scakville)
**DPIE-mc**       (main channel)
**WNSW**
**Hornsby**

a) replot field data with new symbols
b) add SWC ww data
c) make summary table or SWC to check
d) update DataSummary
e) report if high-frequency data is daily averaged
f) finalise scales and style
g) archive old working files to prevent confusion
h) request final-sign off

**Comment by brendan-busch** [comment]
additional: Fix date errors where raw data contains random US formatted dates.

**Comment by matthipsey** [comment]
### Data Summary Table
An large volume of monitoring data is collected for HN for a range of sites. The data used for model testing and validation is compiled into agency resolved data files (.mat). The ones currently used are summarised below.


**Data Sources and Status**



| Label | Agency | Description        |  Date Range | Files  |
| ----- | --------| ----------------------- |:-------------|:--------------------------:|
| `SWC` | SWC | SWC routine data & US/DS data | 01-2005 to 12/2018 | ... |
| `SWC-ww` | SWC | Wet & Dry intensive sampling |05-2018 & 11-2018 | ... |
| `DPIE-bouy` | DPIE (EES) | Sackville Buoy | 01-2018 to 12/2018 | ... |
| `DPIE-mc` | DPIE (EES)  | ... | 05-2017 to 01-2018 | ... |
| `WNSW` | WaterNSW | ... | 01-2005 to 12-2018 | ... |
| `Hornsby` | HSC | ... | 01-2012 to 12-2018 | ... |

**Comment by brendan-busch** [comment]
Data imported and reclassified with new agency codes. WW data still to be imported.

**Comment by brendan-busch** [comment]
WW data imported. Some minor fixes to data import and validation site co-ords based on grid "errors".

Final 10 year images to be plotted and sign off by client.

**Comment by brendan-busch** [comment]
Images uploaded to client. Closed
