### ISSUE TITLE
Transect validation plot

### ISSUE THREAD

**Issue by matthipsey** [AquaticEcoDynamics/Hawkesbury#3]
Along-river (longitudinal) plot  

Zone (maybe sub-zone?) box-whiskers or violins of data distribution.

To be discussed.

**Comment by brendan-busch** [comment]
Rough list of jobs GIS work


- Build a center polyline.
- Convert polyline to station points
- Calculate distances along line
- Calculate regular interval distances (5km or 10km).
- Build fieldsite polygons at 10km intervals.

**Comment by brendan-busch** [comment]
Script on github and images passed onto the client. Closed
