### ISSUE TITLE
New 2D ICs

### ISSUE THREAD

**Issue by matthipsey** [AquaticEcoDynamics/Hawkesbury#4]
Overwrite current ICs to be good

**Comment by brendan-busch** [comment]
Initial conditions spreadsheet check in. Needs discussion.

**Comment by brendan-busch** [comment]
Simulations 2013 & 2017 running. Results to be plotted and spreadsheets refined as needed.

**Comment by brendan-busch** [comment]
Salinity is incorrect in the IC files. Reviewing the code and changes will be in V4_A4 simulations

**Comment by brendan-busch** [comment]
Salinity and Temperature updated in IC files for 2013 & 2017. Test sims now running on Mickey and Pugsy

**Comment by brendan-busch** [comment]
Code run and tested. Minor tweaks may occur but issue considered closed
